baseURL = "https://example.org"

[taxonomies]
  tag = "tags"
  creator = "creators"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.75.0"

    [[module.imports]]
    path = 'github.com/team-durumi/hugo-search-fuse-js-aa'
    disable = false

[build]
# Used by PurgeCSS
writeStats = true