baseURL = "https://example.org"

[taxonomies]
  tag = "tags"
  creator = "creators"

paginate = "5"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.75.0"

[build]
# Used by PurgeCSS
writeStats = true